# ============================
# Google Ads MCC Data Fetcher - Complete Configuration
# ملف الإعدادات الكامل لجالب بيانات Google Ads MCC
# ============================

# إعدادات Google Ads API الأساسية - مطلوبة
developer_token: "ttkK6FCgnU2EjF43wt3lhQ"
client_id: "366144291902-u75bec3sviur9nrutbslt14ob14hrgud.apps.googleusercontent.com"
client_secret: "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"
refresh_token: "1//040G6YqK7TSaJCgYIARAAGAQSNwF-L9IrWnLD8jXYWoZ7QTF-dCO1anFae18dGCdxljCHVsMYVtrE8_BWkGIj7CPIqW106XcuBk0"
login_customer_id: "9252466178"
use_proto_plus: true

# إعدادات البيئة
environment:
  current: "production"
  auto_detect: false
  config_validation: true
  schema_validation: false

# معلومات الحساب
account:
  customer_id: "9252466178"
  developer_token: "ttkK6FCgnU2EjF43wt3lhQ"
  login_customer_id: "9252466178"
  account_type: "MCC"
  account_tier: "ENTERPRISE"

# إعدادات OAuth2
oauth2:
  client_id: "366144291902-u75bec3sviur9nrutbslt14ob14hrgud.apps.googleusercontent.com"
  client_secret: "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"
  refresh_token: "1//040G6YqK7TSaJCgYIARAAGAQSNwF-L9IrWnLD8jXYWoZ7QTF-dCO1anFae18dGCdxljCHVsMYVtrE8_BWkGIj7CPIqW106XcuBk0"
  auto_refresh: true

# إعدادات التسجيل
logging:
  level: "INFO"
  format: "text"
  file_rotation: true
  max_file_size: "10MB"
  backup_count: 5

# إعدادات طلبات API
api_requests:
  timeout_seconds: 120
  max_retries: 5
  initial_retry_delay_seconds: 1
  max_retry_delay_seconds: 60
  retry_on_errors: true

# إعدادات معالجة الأخطاء
error_handling:
  max_retry_attempts: 5
  initial_retry_delay_seconds: 1
  max_retry_delay_seconds: 60
  exponential_backoff: true
  jitter: true
  circuit_breaker_enabled: true
  circuit_breaker_failure_threshold: 10
  circuit_breaker_recovery_timeout: 300

# إعدادات الأداء
performance:
  max_workers: 8
  batch_size: 1000
  parallel_processing: true
  memory_optimization: true
  cache_enabled: true
  cache_ttl_seconds: 3600

# إعدادات التصدير
export:
  formats: ["excel", "csv", "json", "html"]
  excel_engine: "openpyxl"
  csv_encoding: "utf-8"
  json_indent: 2
  html_template: "default"

# إعدادات التحليل والذكاء الاصطناعي
analytics:
  ai_insights_enabled: true
  trend_analysis_enabled: true
  performance_benchmarking: true
  anomaly_detection: true
  predictive_analytics: false
  sentiment_analysis: false

# إعدادات المخططات البيانية
visualization:
  enabled: true
  chart_types: ["bar", "line", "pie", "scatter"]
  arabic_text_support: true
  high_resolution: true
  color_scheme: "professional"
  save_format: "png"
  dpi: 300

# إعدادات التقارير
reporting:
  html_reports: true
  pdf_reports: false
  summary_reports: true
  detailed_reports: true
  client_specific_reports: true
  mcc_overview_report: true

# إعدادات الأمان
security:
  encryption_enabled: true
  secure_storage: true
  data_anonymization: false
  audit_logging: true
  access_control: false

# إعدادات البيانات
data:
  date_range: "LAST_30_DAYS"
  include_test_accounts: false
  include_disabled_campaigns: false
  data_freshness_hours: 24
  historical_data_retention_days: 365

# إعدادات الشبكة
network:
  connection_timeout: 30
  read_timeout: 120
  max_connections: 10
  retry_on_connection_error: true
  proxy_enabled: false
  proxy_host: ""
  proxy_port: 0

# إعدادات التخزين
storage:
  base_directory: "google_ads_data"
  create_subdirectories: true
  file_naming_convention: "timestamp"
  compression_enabled: false
  cleanup_old_files: false
  max_storage_size_gb: 10

# إعدادات الإشعارات
notifications:
  email_enabled: false
  email_recipients: []
  slack_enabled: false
  slack_webhook: ""
  success_notifications: false
  error_notifications: true

# إعدادات التطوير والتصحيح
development:
  debug_mode: false
  verbose_logging: false
  dry_run: false
  test_mode: false
  profiling_enabled: false

# إعدادات التوافق
compatibility:
  google_ads_api_version: "v16"
  python_version_check: true
  dependency_validation: true
  backward_compatibility: true

# إعدادات التخصيص
customization:
  custom_fields: []
  custom_metrics: []
  custom_segments: []
  custom_filters: []
  custom_transformations: []

# إعدادات الجودة
quality:
  data_validation: true
  schema_validation: true
  completeness_check: true
  accuracy_threshold: 0.95
  consistency_check: true

# إعدادات المراقبة
monitoring:
  performance_tracking: true
  resource_usage_monitoring: true
  api_quota_monitoring: true
  error_rate_monitoring: true
  health_checks: true

# إعدادات التكامل
integration:
  external_apis: []
  webhooks: []
  data_pipelines: []
  third_party_tools: []

# إعدادات النسخ الاحتياطي
backup:
  enabled: false
  frequency: "daily"
  retention_days: 30
  compression: true
  remote_storage: false

# إعدادات الصيانة
maintenance:
  auto_cleanup: true
  log_rotation: true
  cache_cleanup: true
  temp_file_cleanup: true
  scheduled_maintenance: false

